# Generated by Django 5.0.6 on 2024-06-10 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudberries', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AddField(
            model_name='post',
            name='summary',
            field=models.CharField(default='placeholde', max_length=200),
            preserve_default=False,
        ),
    ]
