# Generated by Django 5.0.6 on 2024-06-24 17:49
from datetime import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudberries', '0004_tutorial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='body',
            field=models.TextField(default="temp"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=datetime.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='project',
            name='summary',
            field=models.CharField(default="temp", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='title',
            field=models.CharField(default="temp", max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tutorial',
            name='body',
            field=models.TextField(default="temp"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tutorial',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=datetime.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tutorial',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='summary',
            field=models.CharField(default="temp", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tutorial',
            name='title',
            field=models.CharField(default="temp", max_length=256),
            preserve_default=False,
        ),
    ]
