# Generated by Django 5.0.6 on 2024-06-30 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudberries', '0007_upload'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upload',
            old_name='file_name',
            new_name='body_file',
        ),
        migrations.AddField(
            model_name='upload',
            name='meta_file',
            field=models.FileField(default=None, upload_to='post_uploads'),
            preserve_default=False,
        ),
    ]
