# Generated by Django 5.0.6 on 2024-06-30 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudberries', '0008_rename_file_name_upload_body_file_upload_meta_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='post_type',
            field=models.CharField(choices=[('post', 'Post'), ('tutorial', 'Tutorial'), ('project', 'Project')], default='post', max_length=32),
        ),
    ]
